# This is a basic workflow to help you get started with Actions

name: check all docs are linked to index

# Controls when the action will run. Triggers the workflow on push or pull request
# events but only for the master branch
on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      - name: checkout repo
        uses: actions/checkout@v2.3.4
      - name: ls
        run: | 
          ls .
      - name: Calculate not indexed folders
        run: ROOT_DIRS=$(find . -mindepth 1 -maxdepth 1 -type d -printf '%P\n' | grep -v 'docs\|\.' | sort | grep '.') && DOCS_DIRS=$(find docs -mindepth 1 -maxdepth 1 -type l -printf '%P\n' | sort | grep '.') && comm -3 <(echo "$ROOT_DIRS") <(echo "$DOCS_DIRS") > not_indexed_folders
      - name: Check if not indexed folders list is empty
        run: |
          if [ -s not_indexed_folders ]; then
              echo -e "::error::Please add symlinks in docs to next folders:\n$(cat not_indexed_folders)"
              exit 1
          fi
